services:
  web:
    build: .
    container_name: drf_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    extra_hosts:
      - "host.docker.internal:hfost-gateway"

    environment:
      DB_NAME: drfdb
      DB_USER: drfuser
      DB_PASSWORD: password
      DB_HOST: 172.17.0.1
      DB_PORT: 3306