version: '3.9'

services:
  web:
    build: .
    container_name: drf_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      DB_NAME: drfdb
      DB_USER: drfuser
      DB_PASSWORD: password
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    ports:
      - "8000:8000"
    

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: drfdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

